name: oak ci

on: [push, pull_request]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Deno
        run: curl -L https://deno.land/x/install/install.sh | sh -s "v1.0.0"
      - name: Run Tests
        run: ~/.deno/bin/deno test --allow-read
