name: oak ci

on: [push, pull_request]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Run Tests
        run: |
          curl -L https://deno.land/x/install/install.sh | sh -s "v1.0.0"
          export PATH="$HOME/.deno/bin:$PATH"
          deno test --allow-read
